### ISSUE TITLE
Standup Log

### ISSUE THREAD

**Issue by Dalmano** [fac-graduate-programme/Esmee-Fairbairn-Foundation#1]

**Comment by dubhcait** [comment]
Date:2nd Sep

What issue(s) did I work on today?
- Logged into salesforce to get a feel for it
- took a looked at the documentation for some of the salesforce API. [there is soo much]
-  watched  https://www.youtube.com/watch?v=UI0f34Chsvk. Not a great video.
 uses https://www.npmjs.com/package/jsforce [seems like a good idea to try this node module]
 
What issue do I plan to work on tomorrow?
Workshop with Josh.

Am I facing any blockers?
nope

**Comment by Dalmano** [comment]
Date: 2nd Sep

What issue(s) did I work on today?
- Went through the current quiz on Esme Fairbairn's website prior to the application form. 
- Looked into documention about salesforceAPI 

What issue do I plan to work on tomorrow?
- Workshop 2 with josh
- Figma

Am I facing any blockers?
no

**Comment by dubhcait** [comment]
Date: 3rd Sep

What issue(s) did I work on today?
began a demo of netlify functions. worked with a callback. 
Tried to connect using JSforce module to the API to salesforce, got a response but our account doesnt have authorisation for third party apps aka the API. 

What issue do I plan to work on tomorrow?
change demo to async-await. 
set up dev acc with salesForce - link demo to it

Am I facing any blockers?
nope

**Comment by AbdallahAmmar96** [comment]
@dubhcait 
I have the same problem in the salesforce
API is not enabled for this Organization or Partner

**Comment by Dalmano** [comment]
Date: 3rd Sep

What issue(s) did I work on today?
Started working on Figma 

What issue do I plan to work on tomorrow?
Figma

Am I facing any blockers?
Nope

**Comment by sallamTanna** [comment]
Sallam & Abdullah

Date: 4th Sep

What issue(s) did we work on today?
Improving the Figma prototype. 

What issue do we plan to work on tomorrow?
Trying to finish with Figma.

Are we facing any blockers?
No.

**Comment by Dalmano** [comment]
Dylan and Kate

Date: 4th Sep

What issue(s) did I work on today?
Figma

What issues do I plan to work on tomorrow?
Finishing Figma

Am I facing any blockers?
no

**Comment by Dalmano** [comment]
Date: 5th Sep

What issue(s) did I work on today?
Finished Figma and form sending leads to salesforce 

What issues do I plan to work on tomorrow?
Tackle salesforce 

Am I facing any blockers?

**Comment by dubhcait** [comment]
Date: 5th Sep

What issue(s) did I work on today?
Finished Figma 
Research: Heroku and salesForce

![](https://i.imgur.com/vyUpvLw.png)


![](https://i.imgur.com/eeA53wC.png)


The data needs to be manipulatable in salesforce so Heroku connect sync is better 

https://www.youtube.com/watch?v=SZhhyDuQHp4

What issues do I plan to work on tomorrow?
Set up initial file structure 

Am I facing any blockers?
nope

**Comment by sallamTanna** [comment]
Date: 5th Sep

What issue(s) did I work on today?
Improving Figma
Discussing how to handle the application data using salesforce

What issues do I plan to work on tomorrow?
Edit Figma as the client wants after testing it.
Start writing issues on GitHub.

Am I facing any blockers?
no

**Comment by dubhcait** [comment]
Date: 6th Sep

What issue(s) did I work on today?
Created file structure
Started writing issues on GitHub.

What issues do I plan to work on tomorrow?
Monday - work on components

Am I facing any blockers?
no

**Comment by Dalmano** [comment]
Date: 6th Sep

What issue(s) did I work on today?
Screenshotted the quiz and made a Figma for the flow.
Made issues and labelled them 

What issues do I plan to work on tomorrow?
Make components 

Am I facing any blockers?
no

**Comment by sallamTanna** [comment]
Date: 8th Sep

What issue(s) did I work on today?
Creating some component. 

What issues do I plan to work on tomorrow?
Continue with the component.

Am I facing any blockers?
no

**Comment by Dalmano** [comment]
Dylan and Kate
Date: 9th Sep

What issue(s) did I work on today?
Attempted creating a new object in Salesforce...couldn't do it so created a developers salesforce account. 
Using SQL DB to send information to salesforce. 
Made popup modal

What issues do I plan to work on tomorrow?
Work on linking it to new text account we made today.
Create custom objects and mapping through those.
Finish modal.

Am I facing any blockers?
Need to see what's been written code-wise to see what needs to be done and how it will fit together.

**Comment by sallamTanna** [comment]
Date: 9th Sep

What issue(s) did I work on today?
Creating some components 

What issues do I plan to work on tomorrow?
Continue with components 

Am I facing any blockers?
No

**Comment by sallamTanna** [comment]
Date: 10th Sep

What issue(s) did I work on today?
Creating some components

What issues do I plan to work on tomorrow?
Finish front-end and start working with back-end

Am I facing any blockers?
No

**Comment by dubhcait** [comment]
Date: 10th Sep

What issue(s) did I work on today?
Connectod sql database with heroku connect

What issues do I plan to work on tomorrow?
start working on backend routes

Am I facing any blockers?
No

**Comment by sallamTanna** [comment]
Date: 15th Sep

What issue(s) did I work on today?
Finishing /question route

What issues do I plan to work on tomorrow?
Finishing adding /question inside App.js

Am I facing any blockers?
Heroku connect had some troubles that I couldn't get any response from salesforce. I solved that by removing the old map and adding a new one with a new custom object(which is exactly the same with the previous one)

**Comment by sallamTanna** [comment]
Date: 16th Sep

What issue(s) did I work on today?
Finishing adding the /question inside App.js and test the route.

What issues do I plan to work on tomorrow?
Discuss the stretch goals and test the local database.

Am I facing any blockers?
No

**Comment by Dalmano** [comment]
Date: 17th Sep

What issue(s) did I work on today?
Google Analytics

What issues do I plan to work on tomorrow?
Google Analytics

Am I facing any blockers?
No

**Comment by sallamTanna** [comment]
Date: 17th Sep  

 Did noting, I was sick :mask:

**Comment by sallamTanna** [comment]
Date: 18th Sep

What issue(s) did I work on today?
Start working with QuizPage, fix some issues in QuestionsPage

What issues do I plan to work on tomorrow?
Finish QuestionsPage

Am I facing any blockers?
No

**Comment by sallamTanna** [comment]
Date: 19th Sep

What issue(s) did I work on today?
Finish QuizPage, fix some issues in QuestionsPage 

What issues do I plan to work on tomorrow (22/9)?
Review database testing 

Am I facing any blockers?
No

**Comment by sallamTanna** [comment]
Date: 22nd Sep

What issue(s) did I work on today?
Finish database testing, remove finished issues 

What issues do I plan to work on tomorrow?
Discuss how to improve the app

Am I facing any blockers?
No
