### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by AbdallahAmmar96** [fac-graduate-programme/Esmee-Fairbairn-Foundation#20]
We can add package.json in the server folder instead of adding it in the root 
(there is no need for it in the root). As the project must be divided into two parts 
(front end and backend ) especially we are working with react  
so we can have two package.json in the project 
the first in client-side 
the second in the server-side

**Comment by sallamTanna** [comment]
Good idea.

**Comment by dubhcait** [comment]
Interesting, How would that work with deployment? Currently, it works with proxying the react endpoints out and I think( correct me if I'm wrong) that requires that the backend's package.json be in root.

**Comment by AbdallahAmmar96** [comment]
In the deployment phase, we won't use the react server at all.
because we make the build the react and put the build folder in the back-end server.
There will be one server ( The back-end server ) and we won't need to proxy our requests.
@dubhcait
