### ISSUE TITLE
Schema Discussion 

### ISSUE THREAD

**Issue by Dalmano** [fac-graduate-programme/Esmee-Fairbairn-Foundation#29]
We will build it in Salesforce and sync it to SQL.

For the Questions table, we will have: heading, subheading, restrictions, wordcount.

This will be built through Heroku connect and Salesforce dashboard rather than a build script which provides more functionality. 

For the Answers table, we will have 3 columns 1, 2, 3 in relation to the questions.

What are your thoughts?

**Comment by sallamTanna** [comment]
What about renaming the fields in Questions table so they match the names I used in front-end?
They are: title, expectations, tips, wordsLimit
