### ISSUE TITLE
React Routing 

### ISSUE THREAD

**Issue by dubhcait** [fac-graduate-programme/Esmee-Fairbairn-Foundation#37]
Setup navigation in app.js

https://reacttraining.com/react-router/

After pages are done

**Comment by AbdallahAmmar96** [comment]
We don't need a react-router for our project
just one page

**Comment by dubhcait** [comment]
Ok well then the equivalent logic to app.js to conditionally render components,
 We can add a index.js to our pages directory so we only need to import that and deconstruct the individual pages from it?
