### ISSUE TITLE
Create file structure

### ISSUE THREAD

**Issue by sallamTanna** [fac-graduate-programme/Esmee-Fairbairn-Foundation#4]
We will use React.js (create-react-app) for the front-end, and Express.js for the back-end.  Based on the Figma prototype, the file structure may look like the following structure

### Client-side
* public folder
  - index.html
* src folder
   - components folder
     - App component 
     - Button component
     - PopUp component 
     - Tabs component
        - Tab component
        - TabBody component
        - Textarea button
        - Review component
   -  pages folder
      - Welcome page
      - Questions page
      - Note page
      - Tips page
   - assets folder 
  - utils folder
   - index.js
### Server-side
* controllers folder
* app.js
* index.js

**Comment by AbdallahAmmar96** [comment]
For the client-side move the app.js into the component folder @dubhcait 
and add .gitignore file.
there is no need for the TabBody component !!
and add text field component

**Comment by dubhcait** [comment]
what benefit is there to putting the app.js in the component folder? Plus we don't need multiple .gitignore files in one repo.

**Comment by AbdallahAmmar96** [comment]
It's not about benefit, just a structer for the files and it's known is just the index.js will be in the root of folder.
about .gitignor we need it because the project must be two parts and no one depend on the other

**Comment by sallamTanna** [comment]
@AbdallahAmmar96 No need for text field component. It is going to be used once inside the "TabBody component"
