### ISSUE TITLE
Inconsistent widths

### ISSUE THREAD

**Issue by dubhcait** [fac-graduate-programme/Esmee-Fairbairn-Foundation#85]
Is this the same for everyone

![image](https://user-images.githubusercontent.com/39469813/65155619-81edc800-da25-11e9-93cf-4a65bb8b909f.png)

![image](https://user-images.githubusercontent.com/39469813/65155664-95009800-da25-11e9-9bdf-01811d63005a.png)

**Comment by sallamTanna** [comment]
Hehehe yes,
I will fix the width, so the Tabs will not resize
